---
- hosts: all
  remote_user: centos
  tasks:
  - name: Install docker
    yum:
      name: docker
      state: installed
    become: yes
  - name: Install epel-release
    yum:
      name: epel-release
      state: installed
    become: yes
  - name: Install pip
    yum:
      name: python-pip
      state: installed
    become: yes
  - name: Install docker-compose
    pip:
      name:
        - docker-compose
        - docker-py
    become: yes
  - name: Run docker
    service:
      name: docker
      state: started
    become: yes
  - name: Add registry ip in hosts
    lineinfile:
      dest: /etc/hosts
      line: '172.31.1.248 ci-dms.ap.aws.griddynamics.net'
      state: present
    become: yes
...
