---
- hosts: "{{ host }}"
  remote_user: centos
  tasks:
  - name: Log into registry and force re-authorization
    docker_login:
      registry: "{{ registry_url }}"
      username: "{{ username }}"
      password: "{{ password }}"
      reauthorize: yes
    become: yes
  - name: Container start
    docker_container:
      name: dms-assistant
      state: started
      image: "{{ image }}"
      ports:
       - "80:8080"
      env:
          SPRING_PROFILES_ACTIVE: "{{ profile }}"
          SPRING_MAIL_HOST: "{{ smtp_host }}"
          SPRING_MAIL_USERNAME: "{{ smtp_username }}"
          SPRING_MAIL_PASSWORD: "{{ smtp_password }}"
          SPRING_MAIL_PROPERTIES_MAIL_SMTP_PORT: "{{ smtp_port }}"
          SPRING_MAIL_PROPERTIES_MAIL_SMTP_AUTH: "{{ smtp_auth }}"
          SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_ENABLE: "{{ smtp_starttls_enable }}"
          ADMIN: "{{ admin }}"
          HOST: "{{ link }}"
    become: yes
  - name: Wait for application up
    wait_for:
      host: localhost
      port: 80
      delay: 10
      timeout: 30
      state: drained
...
